# Generated by Django 5.2 on 2025-05-02 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singup', '0003_patients_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(max_length=25)),
                ('department', models.CharField(max_length=25)),
                ('doctor', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singup.patients')),
            ],
        ),
    ]
