# Generated by Django 5.2.1 on 2025-06-13 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0002_delete_appointment'),
        ('doctor', '0001_initial'),
        ('singup', '0003_patients_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=500)),
                ('phone', models.BigIntegerField()),
                ('department', models.CharField(max_length=25)),
                ('doctor', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('status', models.CharField(default='Pending', max_length=25)),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singup.patients')),
            ],
        ),
    ]
