# Generated by Django 5.2.1 on 2025-07-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone',
        ),
    ]
