# Generated by Django 5.2.1 on 2025-09-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_rename_time_appointment_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
