# Generated by Django 5.2.1 on 2025-09-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_appointment_end_time_appointment_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
