# Generated by Django 5.2.1 on 2025-09-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_remove_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_attend',
            field=models.BooleanField(default=False),
        ),
    ]
